load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_java//java:defs.bzl", "java_proto_library")

# Build adblib as a standalone library, with side effect of ensuring that adblib does not
# use unwanted dependencies from "studio-sdk" in the iml_module rule above
# Build with: bazel build //tools/base/adblib:adblib
kt_jvm_library(
    name = "adblib",
    srcs = glob([
        "src/**/*.kt",
    ]),
    deps = [
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib_jdk8",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core",
        # Required to build the java file generated by ":app-processes-proto" rule
        "@maven//:com_google_protobuf_protobuf_java",
        # See rule at end of this file
        ":app-processes-java-proto",
    ],
)

#
# Rule to compile 'proto/app_processes.proto' for the stand-alone "kotlin_library" version
# of adblib. This compiles the proto into the "com.android.server.adb.protos" package.
#
java_proto_library(
    name = "app-processes-java-proto",
    deps = [":app-processes-proto"],
)

proto_library(
    name = "app-processes-proto",
    srcs = glob(["proto/app_processes.proto"]),
)
